---
categories:
  Actions:
    - Button
    - Dropdown
    - Modal
    - Swap
    - ThemeController
  Data display:
    - Badge
    - Card
    - Accordion
    - Avatar
    - Carousel
    - ChatBubble
    - Collapse
    - Countdown
    - Diff
    - Kbd
    - Stat
    - Table
    - Timeline
  Data Input:
    - Checkbox
    - FileInput
    - Radio
    - Range
    - Rating
    - Select
    - TextInput
    - Textarea
    - Toggle
    - FormControl
  Layout:
    - Artboard
    - Divider
    - Drawer
    - Footer
    - Hero
    - Indicator
    - Join
    - Mask
    - Stack
  Mockup:
    - Browser
    - Code
    - Phone
    - Window
  Feedback:
    - Loading
    - Alert
    - Progress
    - RadialProgress
    - Skeleton
    - Toast
    - Tooltip
  Navigation:
    - Menu
    - Link
    - Breadcrumbs
    - BottomNavigation
    - Navbar
    - Pagination
    - Steps
    - Tab
